import torch
import torch.nn.functional as F

from typing import Optional

from .base import BaseAttentionAgg
from mypt.building_blocks.mixins.general import NonSequentialModuleMixin

class FlashAttentionAttAgg(NonSequentialModuleMixin, BaseAttentionAgg):
    """FlashAttention-powered aggregation stage using PyTorch's optimized implementation."""

    def __init__(
        self,
        num_heads: int,
        value_dim: int,
        key_dim: int,
        dropout: float = 0.0,
        is_causal: bool = False,
    ) -> None:
        """
        Args:
            dropout: Dropout probability for attention weights
            is_causal: Whether to apply causal masking
        """
        BaseAttentionAgg.__init__(self, num_heads=num_heads, value_dim=value_dim, key_dim=key_dim)
        NonSequentialModuleMixin.__init__(self, inner_components_fields=[])
        
        self.dropout = dropout
        self.is_causal = is_causal

    def forward(
        self,
        q: torch.Tensor,
        k: torch.Tensor,
        v: torch.Tensor,
        *,
        mask: Optional[torch.Tensor] = None,
    ) -> torch.Tensor:
        """Compute attention using PyTorch's FlashAttention.
        
        Args:
            q: Query tensor (B, H, S_q, D_k) as generated by the ProjectBase class 
            k: Key tensor (B, H, S_k, D_k) as generated by the ProjectBase class
            v: Value tensor (B, H, S_k, D_v) as generated by the ProjectBase class
            mask: Custom attention mask (B, H, S_q, S_k)
            
        Returns:
            Output tensor (B, H, S_q, D_v)
        """
        # TODO: understand the padding and mask in the pytorch implementation

        # Use PyTorch's optimized implementation
        output = F.scaled_dot_product_attention(
            q, k, v,
            attn_mask=mask,
            dropout_p=self.dropout if self.training else 0.0,
            is_causal=self.is_causal,
        )
        
        # Reorder back to (B, H, S, D) format
        return output.transpose(1, 2)  # (B, H, S_q, D_v)

    def __call__(
        self,
        q: torch.Tensor,
        k: torch.Tensor,
        v: torch.Tensor,
        *,
        attn_mask: Optional[torch.Tensor] = None,
        key_padding_mask: Optional[torch.Tensor] = None,
    ) -> torch.Tensor:
        return self.forward(q, k, v, attn_mask=attn_mask, key_padding_mask=key_padding_mask)